# This code has been generated by python script
execute if score #game NoCoords matches 0 run data merge block ~-2 ~1 ~ {Text3:'{"text":"[Disabled]","color":"red"}'}
execute if score #game NoCoords matches 1 run data merge block ~-2 ~1 ~ {Text3:'{"text":"[Enabled]","color":"green"}'}
execute if score #game FallDamage matches 0 run data merge block ~-1 ~1 ~ {Text3:'{"text":"[Disabled]","color":"red"}'}
execute if score #game FallDamage matches 1 run data merge block ~-1 ~1 ~ {Text3:'{"text":"[Enabled]","color":"green"}'}
execute if score #game ShowPrgress matches 0 run data merge block ~-2 ~0 ~ {Text3:'{"text":"[Disabled]","color":"red"}'}
execute if score #game ShowPrgress matches 1 run data merge block ~-2 ~0 ~ {Text3:'{"text":"[Enabled]","color":"green"}'}
execute if score #game DeathMsg matches 0 run data merge block ~-1 ~0 ~ {Text3:'{"text":"[Disabled]","color":"red"}'}
execute if score #game DeathMsg matches 1 run data merge block ~-1 ~0 ~ {Text3:'{"text":"[Enabled]","color":"green"}'}
execute if score #game Teams matches 0 run data merge block ~1 ~1 ~ {Text3:'{"text":"[Disabled]","color":"red"}'}
execute if score #game Teams matches 1 run data merge block ~1 ~1 ~ {Text3:'{"text":"[Enabled]","color":"green"}'}
execute if score #game RandTeams matches 0 run data merge block ~2 ~1 ~ {Text3:'{"text":"[Disabled]","color":"red"}'}
execute if score #game RandTeams matches 1 run data merge block ~2 ~1 ~ {Text3:'{"text":"[Enabled]","color":"green"}'}
execute if score #game UHCMode matches 0 run data merge block ~1 ~0 ~ {Text3:'{"text":"[Disabled]","color":"red"}'}
execute if score #game UHCMode matches 1 run data merge block ~1 ~0 ~ {Text3:'{"text":"[Enabled]","color":"green"}'}
execute if score #game DoInsomnia matches 0 run data merge block ~2 ~0 ~ {Text3:'{"text":"[Disabled]","color":"red"}'}
execute if score #game DoInsomnia matches 1 run data merge block ~2 ~0 ~ {Text3:'{"text":"[Enabled]","color":"green"}'}