# Generated by python script
execute as @r[team=TEAM_1, tag=InGame] run tag @a[team=TEAM_1] add Winner
execute as @r[team=TEAM_1, tag=InGame] run scoreboard players add @a[team=TEAM_1] Wins 1
execute as @r[team=TEAM_2, tag=InGame] run tag @a[team=TEAM_2] add Winner
execute as @r[team=TEAM_2, tag=InGame] run scoreboard players add @a[team=TEAM_2] Wins 1
execute as @r[team=TEAM_3, tag=InGame] run tag @a[team=TEAM_3] add Winner
execute as @r[team=TEAM_3, tag=InGame] run scoreboard players add @a[team=TEAM_3] Wins 1
execute as @r[team=TEAM_4, tag=InGame] run tag @a[team=TEAM_4] add Winner
execute as @r[team=TEAM_4, tag=InGame] run scoreboard players add @a[team=TEAM_4] Wins 1
execute as @r[team=TEAM_5, tag=InGame] run tag @a[team=TEAM_5] add Winner
execute as @r[team=TEAM_5, tag=InGame] run scoreboard players add @a[team=TEAM_5] Wins 1
execute as @r[team=TEAM_6, tag=InGame] run tag @a[team=TEAM_6] add Winner
execute as @r[team=TEAM_6, tag=InGame] run scoreboard players add @a[team=TEAM_6] Wins 1
execute as @r[team=TEAM_7, tag=InGame] run tag @a[team=TEAM_7] add Winner
execute as @r[team=TEAM_7, tag=InGame] run scoreboard players add @a[team=TEAM_7] Wins 1
execute as @r[team=TEAM_8, tag=InGame] run tag @a[team=TEAM_8] add Winner
execute as @r[team=TEAM_8, tag=InGame] run scoreboard players add @a[team=TEAM_8] Wins 1
execute as @r[team=TEAM_9, tag=InGame] run tag @a[team=TEAM_9] add Winner
execute as @r[team=TEAM_9, tag=InGame] run scoreboard players add @a[team=TEAM_9] Wins 1
execute as @r[team=TEAM_10, tag=InGame] run tag @a[team=TEAM_10] add Winner
execute as @r[team=TEAM_10, tag=InGame] run scoreboard players add @a[team=TEAM_10] Wins 1
execute as @r[team=TEAM_11, tag=InGame] run tag @a[team=TEAM_11] add Winner
execute as @r[team=TEAM_11, tag=InGame] run scoreboard players add @a[team=TEAM_11] Wins 1
execute as @r[team=TEAM_12, tag=InGame] run tag @a[team=TEAM_12] add Winner
execute as @r[team=TEAM_12, tag=InGame] run scoreboard players add @a[team=TEAM_12] Wins 1
execute as @r[team=TEAM_13, tag=InGame] run tag @a[team=TEAM_13] add Winner
execute as @r[team=TEAM_13, tag=InGame] run scoreboard players add @a[team=TEAM_13] Wins 1
execute as @r[team=TEAM_14, tag=InGame] run tag @a[team=TEAM_14] add Winner
execute as @r[team=TEAM_14, tag=InGame] run scoreboard players add @a[team=TEAM_14] Wins 1
execute as @r[team=TEAM_15, tag=InGame] run tag @a[team=TEAM_15] add Winner
execute as @r[team=TEAM_15, tag=InGame] run scoreboard players add @a[team=TEAM_15] Wins 1
execute as @r[team=TEAM_16, tag=InGame] run tag @a[team=TEAM_16] add Winner
execute as @r[team=TEAM_16, tag=InGame] run scoreboard players add @a[team=TEAM_16] Wins 1
execute as @r[team=TEAM_17, tag=InGame] run tag @a[team=TEAM_17] add Winner
execute as @r[team=TEAM_17, tag=InGame] run scoreboard players add @a[team=TEAM_17] Wins 1
execute as @r[team=TEAM_18, tag=InGame] run tag @a[team=TEAM_18] add Winner
execute as @r[team=TEAM_18, tag=InGame] run scoreboard players add @a[team=TEAM_18] Wins 1
execute as @r[team=TEAM_19, tag=InGame] run tag @a[team=TEAM_19] add Winner
execute as @r[team=TEAM_19, tag=InGame] run scoreboard players add @a[team=TEAM_19] Wins 1
execute as @r[team=TEAM_20, tag=InGame] run tag @a[team=TEAM_20] add Winner
execute as @r[team=TEAM_20, tag=InGame] run scoreboard players add @a[team=TEAM_20] Wins 1
execute as @r[team=TEAM_21, tag=InGame] run tag @a[team=TEAM_21] add Winner
execute as @r[team=TEAM_21, tag=InGame] run scoreboard players add @a[team=TEAM_21] Wins 1