#### DO NOT EDIT THIS FILE, IT IS GENERATED FROM PYTHON SCRIPT

team add TEAM_1 "#1"
team modify TEAM_1 prefix "#1 "
team modify TEAM_1 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_1 trigger
team add TEAM_2 "#2"
team modify TEAM_2 prefix "#2 "
team modify TEAM_2 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_2 trigger
team add TEAM_3 "#3"
team modify TEAM_3 prefix "#3 "
team modify TEAM_3 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_3 trigger
team add TEAM_4 "#4"
team modify TEAM_4 prefix "#4 "
team modify TEAM_4 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_4 trigger
team add TEAM_5 "#5"
team modify TEAM_5 prefix "#5 "
team modify TEAM_5 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_5 trigger
team add TEAM_6 "#6"
team modify TEAM_6 prefix "#6 "
team modify TEAM_6 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_6 trigger
team add TEAM_7 "#7"
team modify TEAM_7 prefix "#7 "
team modify TEAM_7 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_7 trigger
team add TEAM_8 "#8"
team modify TEAM_8 prefix "#8 "
team modify TEAM_8 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_8 trigger
team add TEAM_9 "#9"
team modify TEAM_9 prefix "#9 "
team modify TEAM_9 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_9 trigger
team add TEAM_10 "#10"
team modify TEAM_10 prefix "#10 "
team modify TEAM_10 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_10 trigger
team add TEAM_11 "#11"
team modify TEAM_11 prefix "#11 "
team modify TEAM_11 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_11 trigger
team add TEAM_12 "#12"
team modify TEAM_12 prefix "#12 "
team modify TEAM_12 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_12 trigger
team add TEAM_13 "#13"
team modify TEAM_13 prefix "#13 "
team modify TEAM_13 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_13 trigger
team add TEAM_14 "#14"
team modify TEAM_14 prefix "#14 "
team modify TEAM_14 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_14 trigger
team add TEAM_15 "#15"
team modify TEAM_15 prefix "#15 "
team modify TEAM_15 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_15 trigger
team add TEAM_16 "#16"
team modify TEAM_16 prefix "#16 "
team modify TEAM_16 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_16 trigger
team add TEAM_17 "#17"
team modify TEAM_17 prefix "#17 "
team modify TEAM_17 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_17 trigger
team add TEAM_18 "#18"
team modify TEAM_18 prefix "#18 "
team modify TEAM_18 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_18 trigger
team add TEAM_19 "#19"
team modify TEAM_19 prefix "#19 "
team modify TEAM_19 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_19 trigger
team add TEAM_20 "#20"
team modify TEAM_20 prefix "#20 "
team modify TEAM_20 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_20 trigger
team add TEAM_21 "#21"
team modify TEAM_21 prefix "#21 "
team modify TEAM_21 seeFriendlyInvisibles true
scoreboard objectives add Trig_TEAM_21 trigger
