def main():
    signs = []
    print("Leave entry empty to proceed")
    while True:
        userInput = input("Var name: ")
        if (len(userInput) <= 0):
            break
        signs.append({ "varName": userInput, "x": input("rel x coordinate: "), "z": input("rel z coordinate: ")})
    
    # Generate the code
    print("# This code has been generated by python script")
    for var in signs:
        print("execute if score #game {0} matches 0 run data merge block ~{1} ~{2} ~ {{Text3:\'{{\"text\":\"[Disabled]\",\"color\":\"red\"}}\'}}".format(var["varName"], var["x"], var["z"]))
        print("execute if score #game {0} matches 1 run data merge block ~{1} ~{2} ~ {{Text3:\'{{\"text\":\"[Enabled]\",\"color\":\"green\"}}\'}}".format(var["varName"], var["x"], var["z"]))

main()